import {
    Bot,
    Brain,
    Cloud,
    Code,
    FileSearch,
    FlaskConical,
    GraduationCap,
    Key,
    Network,
    Search,
} from "lucide-react";

export type Tool = { slug: string; title: string; desc: string; isPublish: boolean };
export type Category = { title: string; icon: any; color: string; tools: Tool[] };

export const categories: Category[] = [
    {
        title: "Cryptography & Encoding",
        icon: Key,
        color: "bg-indigo-200",
        tools: [
            { slug: "hash", title: "Hash Tools", desc: "MD5, SHA1, SHA256, SHA512", isPublish: true },
            { slug: "jwt", title: "JWT Decoder", desc: "Decode and verify JWTs", isPublish: true },
            { slug: "jwt-cracker", title: "JWT Cracker", desc: "Test weak signing keys", isPublish: false },
            { slug: "password", title: "Password Utilities", desc: "Strength checker and generator", isPublish: true },
            { slug: "hash-id", title: "Hash Identifier", desc: "Detect type of hash string", isPublish: true },
            { slug: "obfuscator", title: "String Obfuscator", desc: "ROT13, Caesar, XOR, Base conversions", isPublish: true },
            { slug: "cert-parser", title: "Certificate Parser", desc: "PEM/DER certificate details", isPublish: true },
            { slug: "hash-collision", title: "Hash Collision Demo", desc: "Visualize MD5/SHA1 collisions", isPublish: true },
            { slug: "base64", title: "Base64/Base32 Encoder", desc: "Encode/decode Base64, Base32, Base85 with file support", isPublish: true },
            { slug: "pgp", title: "PGP Key Generator", desc: "Generate PGP keys, encrypt/decrypt messages", isPublish: true },
            { slug: "aes-rsa", title: "AES/RSA Encryptor", desc: "Client-side encryption with AES and RSA", isPublish: true },
            { slug: "converter", title: "Unicode/Hex/Binary Converter", desc: "Convert between Unicode, Hex, Binary, Decimal", isPublish: true },
        ],
    },
    {
        title: "Threat Intelligence",
        icon: Search,
        color: "bg-pink-200",
        tools: [
            { slug: "ioc", title: "IOC Extractor", desc: "Extract IPs, URLs, hashes, emails", isPublish: true },
            { slug: "cve", title: "CVE Lookup", desc: "Fetch details from CIRCL CVE", isPublish: true },
            { slug: "cve-feed", title: "CVE Feed Viewer", desc: "Browse latest CVEs from NVD", isPublish: true },
            { slug: "threat", title: "Threat Intel Check", desc: "VirusTotal/AbuseIPDB", isPublish: true },
            { slug: "whois", title: "WHOIS / RDAP", desc: "Ownership & registration", isPublish: true },
            { slug: "email-analyzer", title: "Email Header Analyzer", desc: "Trace spoofing & spam origins", isPublish: true },
            { slug: "qr-code-check", title: "QR Code Security Analyzer", desc: "Scan with your camera or upload a QR code image. The tool decodes and flags risky URLs", isPublish: true },
        ],
    },
    {
        title: "Web & Cloud Security",
        icon: Cloud,
        color: "bg-yellow-200",
        tools: [
            { slug: "headers-check", title: "Security Headers Checker", desc: "Inspect CSP, HSTS, X-Frame-Options", isPublish: true },
            { slug: "url-trace", title: "URL Unshortener & Redirect Tracer", desc: "Expand and trace redirects", isPublish: false },
            { slug: "cvss", title: "CVE Severity Calculator", desc: "Compute CVSS scores", isPublish: true },
            { slug: "aws-s3", title: "AWS S3 Checker", desc: "Test for public/misconfigured buckets", isPublish: false },
            { slug: "cors-check", title: "CORS Tester", desc: "Detect misconfigured Access-Control headers", isPublish: false },
            { slug: "clickjack", title: "Clickjacking Tester", desc: "Frame-busting & X-Frame-Options check", isPublish: false },
            { slug: "csrf", title: "CSRF Token Inspector", desc: "Check CSRF token presence & randomness", isPublish: false },
        ],
    },
    {
        title: "Penetration Testing",
        icon: FlaskConical,
        color: "bg-green-200",
        tools: [
            { slug: "wordlist", title: "Wordlist Generator", desc: "Custom password/wordlists", isPublish: true },
            { slug: "xxe", title: "XXE Payload Generator", desc: "XML external entity injection payloads", isPublish: false },
            { slug: "jwt-fuzzer", title: "JWT Fuzzer", desc: "Tweak claims and signatures", isPublish: false },
            { slug: "command-injection", title: "Command Injection Tester", desc: "Common OS injection payloads", isPublish: false },
        ],
    },
    {
        title: "AI Security",
        icon: Brain,
        color: "bg-purple-200",
        tools: [
            { slug: "prompt-template", title: "Prompt Template Builder", desc: "Create reusable structured prompts (system + user + examples).", isPublish: true },
            { slug: "prompt-abtest", title: "Prompt A/B Tester", desc: "Compare model responses across prompt variations.", isPublish: true },
            { slug: "context-trimmer", title: "Context Trimmer", desc: "Automatically shorten context to stay under token limits.", isPublish: false },
            { slug: "prompt-leak", title: "Prompt Leakage Detector", desc: "Detect system prompt exposure or overfitting.", isPublish: false },
            { slug: "persona-lab", title: "Persona Simulator", desc: "Emulate model behavior under various personas.", isPublish: false },
            { slug: "jailbreak-tester", title: "Jailbreak Tester", desc: "Evaluate prompt-injection and system override attempts.", isPublish: false },
            { slug: "toxicity-checker", title: "Toxicity Classifier", desc: "Detect harmful or biased language in model outputs.", isPublish: false },
            { slug: "hallucination-checker", title: "Hallucination Checker", desc: "Compare generated output with factual references.", isPublish: false },
            { slug: "alignment-score", title: "Alignment Score Tracker", desc: "Rate model safety, honesty, and relevance.", isPublish: false },
            { slug: "agent-flow", title: "Agent Flow Visualizer", desc: "Visualize task-chains and tool-use flows.", isPublish: false },
            { slug: "memory-tester", title: "Task Memory Tester", desc: "Evaluate how well an agent retains prior context.", isPublish: false },
            { slug: "rag-builder", title: "RAG Builder", desc: "Connect documents → embeddings → LLM for retrieval QA.", isPublish: false },
            { slug: "tool-use-sim", title: "Tool Use Simulator", desc: "Simulate agent reasoning and tool calls.", isPublish: false },
        ],
    },
    {
        title: "Learning",
        icon: GraduationCap,
        color: "bg-green-50",
        tools: [
            { slug: "tips", title: "Daily Security Tips", desc: "Flashcards & rotating advice", isPublish: true },
            { slug: "ai-tips", title: "Daily AI Concepts", desc: "Flashcards with short explanations of key AI terms.", isPublish: false },
            { slug: "prompt-labs", title: "Prompt Engineering Playground", desc: "Interactive tutorials for writing better prompts.", isPublish: false },
            { slug: "ai-papers", title: "AI Paper Digest", desc: "Summaries of top LLM research papers weekly.", isPublish: false },
            { slug: "model-explorer", title: "Model Explorer", desc: "Discover and compare open models from HF/Ollama.", isPublish: false },
            { slug: "shortcut-prompt", title: "PromptShortcuts", desc: "shortcut prompt.", isPublish: true },
            { slug: "tts", title: "Text → Voice (TTS)", desc: "Convert text into spoken audio in the browser. Play, pause, tweak voice/pitch/rate, and export text (audio export requires server-side TTS).", isPublish: true },
        ],
    },
];
