"use client";

import React, { useState } from "react";
import {
    Shield,
    AlertTriangle,
    CheckCircle2,
    XCircle,
    Globe,
    Lock,
    Unlock,
    Copy,
    Download,
    Loader2,
    Info,
    ExternalLink,
    Zap
} from "lucide-react";

type CORSResult = {
    url: string;
    origin: string;
    allowOrigin?: string;
    allowCredentials?: string;
    allowMethods?: string;
    allowHeaders?: string;
    exposeHeaders?: string;
    maxAge?: string;
    preflightStatus?: number;
    vulnerabilities: string[];
    recommendations: string[];
    securityScore: number;
};

async function copyText(text: string, onSuccess: () => void) {
    try {
        await navigator.clipboard.writeText(text);
        onSuccess();
    } catch {
        alert("Copy failed");
    }
}

function downloadBlob(content: string, filename: string, mime = "text/plain") {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

function getScoreColor(score: number) {
    if (score >= 80) return "from-emerald-500 to-teal-600";
    if (score >= 60) return "from-blue-500 to-indigo-600";
    if (score >= 40) return "from-amber-500 to-orange-600";
    return "from-red-500 to-pink-600";
}

function getScoreLabel(score: number) {
    if (score >= 80) return "Secure";
    if (score >= 60) return "Good";
    if (score >= 40) return "Moderate";
    return "Vulnerable";
}

export default function CORSChecker() {
    const [url, setUrl] = useState("");
    const [origin, setOrigin] = useState("https://example.com");
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<CORSResult | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    async function testCORS() {
        setError(null);
        setLoading(true);
        setResult(null);

        try {
            if (!/^https?:\/\//i.test(url)) {
                setError("Please enter a valid URL starting with http:// or https://");
                setLoading(false);
                return;
            }

            const res = await fetch("/api/cors-check", {
                method: "POST",
                headers: { "content-type": "application/json" },
                body: JSON.stringify({ url, origin }),
            });

            if (!res.ok) throw new Error(`Server error ${res.status}`);
            const data = await res.json();
            setResult(data);
        } catch (err: any) {
            setError("Failed to test CORS: " + (err.message || String(err)));
        } finally {
            setLoading(false);
        }
    }

    function exportReport() {
        if (!result) return;
        const report = `# CORS Security Report

**Target URL:** ${result.url}
**Test Origin:** ${result.origin}
**Security Score:** ${result.securityScore}/100 (${getScoreLabel(result.securityScore)})

## CORS Headers
- Access-Control-Allow-Origin: ${result.allowOrigin || "Not Set"}
- Access-Control-Allow-Credentials: ${result.allowCredentials || "Not Set"}
- Access-Control-Allow-Methods: ${result.allowMethods || "Not Set"}
- Access-Control-Allow-Headers: ${result.allowHeaders || "Not Set"}
- Access-Control-Expose-Headers: ${result.exposeHeaders || "Not Set"}
- Access-Control-Max-Age: ${result.maxAge || "Not Set"}

## Vulnerabilities Found (${result.vulnerabilities.length})
${result.vulnerabilities.map((v, i) => `${i + 1}. ${v}`).join("\n")}

## Security Recommendations (${result.recommendations.length})
${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

---
Generated by SecuTools.io CORS Tester
`;
        downloadBlob(report, "cors-security-report.md", "text/markdown");
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-violet-50 via-purple-50 to-fuchsia-50 p-4 sm:p-6 lg:p-8">
            <div className="max-w-6xl mx-auto space-y-6">
                {/* Header */}
                <div className="text-center space-y-3">
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/60 backdrop-blur-sm rounded-full border border-purple-200 shadow-sm">
                        <Globe className="w-5 h-5 text-purple-600" />
                        <span className="text-sm font-medium text-purple-900">Web Security</span>
                    </div>
                    <h1 className="text-4xl sm:text-5xl font-bold bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-600 bg-clip-text text-transparent">
                        CORS Security Tester
                    </h1>
                    <p className="text-slate-600 max-w-2xl mx-auto">
                        Test Cross-Origin Resource Sharing configurations, detect misconfigurations,
                        and identify potential security vulnerabilities in your web applications.
                    </p>
                </div>

                {/* Input Card */}
                <div className="bg-white/70 backdrop-blur-xl rounded-2xl shadow-xl border border-white/20 p-6 sm:p-8">
                    <div className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <label className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                                    <Globe className="w-4 h-4 text-purple-600" />
                                    Target URL
                                </label>
                                <input
                                    value={url}
                                    onChange={(e) => setUrl(e.target.value)}
                                    onKeyDown={(e) => e.key === "Enter" && !loading && testCORS()}
                                    className="w-full px-4 py-3 rounded-xl border-2 border-slate-200 focus:border-purple-500 focus:ring-4 focus:ring-purple-100 outline-none transition-all text-slate-800 placeholder:text-slate-400"
                                    placeholder="https://api.example.com/data"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                                    <Shield className="w-4 h-4 text-purple-600" />
                                    Test Origin
                                </label>
                                <input
                                    value={origin}
                                    onChange={(e) => setOrigin(e.target.value)}
                                    onKeyDown={(e) => e.key === "Enter" && !loading && testCORS()}
                                    className="w-full px-4 py-3 rounded-xl border-2 border-slate-200 focus:border-purple-500 focus:ring-4 focus:ring-purple-100 outline-none transition-all text-slate-800 placeholder:text-slate-400"
                                    placeholder="https://example.com"
                                />
                            </div>
                        </div>

                        <button
                            onClick={testCORS}
                            disabled={loading || !url}
                            className="w-full px-8 py-4 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl font-semibold hover:shadow-lg hover:scale-[1.02] active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 transition-all flex items-center justify-center gap-2"
                        >
                            {loading ? (
                                <>
                                    <Loader2 className="w-5 h-5 animate-spin" />
                                    Testing CORS Configuration...
                                </>
                            ) : (
                                <>
                                    <Zap className="w-5 h-5" />
                                    Test CORS Configuration
                                </>
                            )}
                        </button>

                        {error && (
                            <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-xl">
                                <XCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                                <div className="text-sm text-red-800">{error}</div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Results */}
                {result && (
                    <>
                        {/* Security Score */}
                        <div className={`bg-gradient-to-r ${getScoreColor(result.securityScore)} rounded-2xl p-8 text-white shadow-xl`}>
                            <div className="flex items-center justify-between flex-wrap gap-4">
                                <div>
                                    <div className="text-white/80 text-sm font-medium mb-1">Security Score</div>
                                    <div className="text-5xl font-bold">{result.securityScore}/100</div>
                                    <div className="text-white/90 text-lg font-semibold mt-1">{getScoreLabel(result.securityScore)}</div>
                                </div>
                                <div className="flex gap-4">
                                    <div className="text-center">
                                        <div className="text-3xl font-bold">{result.vulnerabilities.length}</div>
                                        <div className="text-white/80 text-sm">Issues</div>
                                    </div>
                                    <div className="text-center">
                                        <div className="text-3xl font-bold">{result.recommendations.length}</div>
                                        <div className="text-white/80 text-sm">Tips</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* CORS Headers */}
                        <div className="bg-white/70 backdrop-blur-xl rounded-2xl shadow-xl border border-white/20 overflow-hidden">
                            <div className="px-6 py-4 bg-gradient-to-r from-violet-600 to-purple-600">
                                <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                                    <Globe className="w-5 h-5" />
                                    CORS Headers Detected
                                </h2>
                            </div>

                            <div className="p-6 space-y-3">
                                {[
                                    { label: "Access-Control-Allow-Origin", value: result.allowOrigin, icon: Globe },
                                    { label: "Access-Control-Allow-Credentials", value: result.allowCredentials, icon: result.allowCredentials === "true" ? Unlock : Lock },
                                    { label: "Access-Control-Allow-Methods", value: result.allowMethods, icon: Zap },
                                    { label: "Access-Control-Allow-Headers", value: result.allowHeaders, icon: Info },
                                    { label: "Access-Control-Expose-Headers", value: result.exposeHeaders, icon: ExternalLink },
                                    { label: "Access-Control-Max-Age", value: result.maxAge, icon: Info },
                                ].map((header, idx) => (
                                    <div
                                        key={idx}
                                        className="flex items-start gap-4 p-4 bg-white rounded-xl border-2 border-slate-200 hover:border-purple-300 transition-all"
                                        style={{ animation: `slideIn 0.3s ease-out ${idx * 0.05}s both` }}
                                    >
                                        <header.icon className="w-5 h-5 text-purple-600 flex-shrink-0 mt-0.5" />
                                        <div className="flex-1 min-w-0">
                                            <div className="text-sm font-semibold text-slate-700">{header.label}</div>
                                            <div className="text-sm text-slate-600 font-mono break-all mt-1">
                                                {header.value || <span className="text-slate-400 italic">Not Set</span>}
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Vulnerabilities */}
                        {result.vulnerabilities.length > 0 && (
                            <div className="bg-white/70 backdrop-blur-xl rounded-2xl shadow-xl border border-red-200 overflow-hidden">
                                <div className="px-6 py-4 bg-gradient-to-r from-red-500 to-pink-600">
                                    <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                                        <AlertTriangle className="w-5 h-5" />
                                        Security Vulnerabilities ({result.vulnerabilities.length})
                                    </h2>
                                </div>

                                <div className="p-6 space-y-3">
                                    {result.vulnerabilities.map((vuln, idx) => (
                                        <div
                                            key={idx}
                                            className="flex items-start gap-3 p-4 bg-red-50 border-2 border-red-200 rounded-xl"
                                            style={{ animation: `slideIn 0.3s ease-out ${idx * 0.05}s both` }}
                                        >
                                            <XCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                                            <div className="text-sm text-red-800">{vuln}</div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Recommendations */}
                        {result.recommendations.length > 0 && (
                            <div className="bg-white/70 backdrop-blur-xl rounded-2xl shadow-xl border border-blue-200 overflow-hidden">
                                <div className="px-6 py-4 bg-gradient-to-r from-blue-500 to-indigo-600">
                                    <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                                        <CheckCircle2 className="w-5 h-5" />
                                        Security Recommendations ({result.recommendations.length})
                                    </h2>
                                </div>

                                <div className="p-6 space-y-3">
                                    {result.recommendations.map((rec, idx) => (
                                        <div
                                            key={idx}
                                            className="flex items-start gap-3 p-4 bg-blue-50 border-2 border-blue-200 rounded-xl"
                                            style={{ animation: `slideIn 0.3s ease-out ${idx * 0.05}s both` }}
                                        >
                                            <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                                            <div className="text-sm text-blue-800">{rec}</div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Export Options */}
                        <div className="flex flex-wrap gap-3">
                            <button
                                onClick={() => copyText(JSON.stringify(result, null, 2), () => {
                                    setCopied(true);
                                    setTimeout(() => setCopied(false), 2000);
                                })}
                                className="px-6 py-3 bg-white border-2 border-slate-300 hover:border-purple-400 rounded-xl text-sm font-semibold text-slate-700 hover:bg-slate-50 transition-all flex items-center gap-2"
                            >
                                <Copy className="w-4 h-4" />
                                {copied ? "Copied!" : "Copy JSON"}
                            </button>
                            <button
                                onClick={exportReport}
                                className="px-6 py-3 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl text-sm font-semibold hover:shadow-lg transition-all flex items-center gap-2"
                            >
                                <Download className="w-4 h-4" />
                                Export Report
                            </button>
                        </div>
                    </>
                )}

                {/* Info Card */}
                <div className="bg-white/50 backdrop-blur-sm rounded-xl border border-slate-200 p-6">
                    <div className="flex items-start gap-3">
                        <Shield className="w-5 h-5 text-purple-600 flex-shrink-0 mt-0.5" />
                        <div className="text-sm text-slate-600">
                            <strong className="text-slate-900">About CORS Testing:</strong> This tool sends test requests to check CORS headers and identifies common misconfigurations like wildcard origins with credentials, overly permissive settings, and missing security headers. Use it to audit your APIs before deployment.
                        </div>
                    </div>
                </div>
            </div>

            <style jsx>{`
        @keyframes slideIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
        </div>
    );
}
